---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: download-manifest-build
spec:
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: build
      image: golang
      script: |
        #!/usr/bin/env bash
        set -xe
        cd /workspace/source
        make
        ./download-manifest --version
        
