---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: download-manifest-build-
spec:
  taskRef:
    name: download-manifest-build
  inputs:
    resources:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: url
              value: https://github.com/doubtingben/download-manifest.git
            - name: revision
              value: test-pr